### ISSUE TITLE
Spampd is doing only local tests, but -L not specified

### ISSUE THREAD

**Issue by the-moog** [mpaperno/spampd#26]
I'm trying to work out why spam is getting though.
It seems spampd is not performing any network tests.
But -L is not supplied on the command line.
Passing a spam message through spamassin -t get scores of >15, but spampd only gives about 3.
I know I'm not running the latests (stock Ubuntu 80.04) is this a known issue?
Version debian/1.42-1
Or perhaps a config issue.
I've specified --debug and can see the startup in the log.
That does not indicate an issue, the network tests ARE on according to log.
But according to injected headers they are not tested.
Some sort of race condition perhaps?

**Comment by mpaperno** [comment]
@the-moog Did you ever figure this out?
