### ISSUE TITLE
Typo and question about signals

### ISSUE THREAD

**Issue by realsimix** [mpaperno/spampd#34]
There is a small typo in current master:

```
--- spampd-master/spampd.pl.orig	2021-08-03 19:39:28.000000000 +0200
+++ spampd-master/spampd.pl	2021-08-04 10:21:15.797812535 +0200
@@ -782,7 +782,7 @@ sub validate_main_opts {
   }
   else {
     eval { require IO::Socket::IP; }
-    or push (@errs, "Error loading IO::IP::UNIX module, required for --relayhost option.\n\t$@");
+    or push (@errs, "Error loading IO::Socket::IP module, required for --relayhost option.\n\t$@");
   }
 
   return (@errs, @warns);
```
I've now also looked at the signal handling and I'm wondering what the proper way would be to terminate SpamPD, be in from init scripts or systemd units.

I've always used SIGTERM but what about using SIGQUIT to have graceful shutdowns?

Thanks,
Simon

**Comment by mpaperno** [comment]
Thanks!  Added to the other pending "documentation" corrections.

Yes, `QUIT` for graceful, `TERM` for immediate.  On a live server I'd certainly (prefer to) try the former first, assuming one can wait at all, then maybe TERM it after a timeout or some such thing.  If one has to force-quit it often that may be an indication of some bigger issue, like hanging spam network checks for example.
